#!/bin/bash

export PYTHONPATH=$(pwd):$PYTHONPATH

export DATAFEEDS_UNDER_TEST="True"
export POSTGRES_URL="postgresql+psycopg2://postgres@pg/gridium"
export LOG_LEVEL="ERROR"
export DEPENDENCY_LOG_LEVEL="ERROR"
export WORKING_DIRECTORY="$(pwd)/workdir"

export URJANET_MYSQL_HOST="urjanet"
export URJANET_MYSQL_USER="gridium"
export URJANET_MYSQL_PASSWORD="gridium"
export URJANET_MYSQL_DB="urjanet"
