on:
  push:
    branches:
      - master

name: Transition Issue to Deploy

jobs:
  transition-issue-to-deploy:
    name: Transition Issue to Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Find issue
      id: find
      uses: atlassian/gajira-find-issue-key@master
      # Do not fail the job if an issue key is not included
      continue-on-error: true
      with: 
        from: commits

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      continue-on-error: true
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: "Deploy"

